# Generated by Django 3.2.8 on 2021-11-22 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0005_alter_shopuser_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopuserprofile',
            name='about_name',
            field=models.TextField(blank=True, null=True, verbose_name='Обо мне'),
        ),
    ]
