# Generated by Django 3.2.8 on 2021-11-23 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0006_alter_shopuserprofile_about_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopuser',
            name='avatar_urls',
            field=models.URLField(default='', verbose_name='Аватар'),
        ),
    ]
