# Generated by Django 3.2.8 on 2021-11-23 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0008_alter_shopuser_avatar_urls'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopuser',
            name='avatar_urls',
        ),
    ]
