# Generated by Django 3.2.8 on 2021-11-24 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orderapp', '0003_alter_order_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='is_active',
        ),
    ]
